parallel-jobs = 1

# ======================================================================
# VIDEO & STREAMING
# ======================================================================

[YouTube]
enabled         = true
app-name        = "YouTube"
build-mode      = "apk"
arch            = "all"
version         = "auto"
patches-source  = "revanced/revanced-patches"
uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube-Moprphe]
enabled         = true
app-name        = "YouTube-Moprphe"
build-mode      = "apk"
arch            = "all"
version         = "auto"
patches-source  = "MorpheApp/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[YouTube-anddea]
enabled         = true
app-name        = "YouTube-anddea"
build-mode      = "apk"
arch            = "all"
version         = "auto"
patches-source  = "anddea/revanced-patches"
uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
