parallel-jobs = 1

# ======================================================================
# MUSIC
# ======================================================================

[Music]
enabled         = true
app-name        = "Music"
build-mode      = "apk"
arch            = "arm64-v8a"
version         = "auto"
patches-source  = "revanced/revanced-patches"
uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Music-Moprphe]
enabled         = true
app-name        = "Music-Moprphe"
build-mode      = "apk"
arch            = "arm64-v8a"
version         = "auto"
patches-source  = "MorpheApp/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[Music-anddea]
enabled         = true
app-name        = "Music-anddea"
build-mode      = "apk"
arch            = "arm64-v8a"
version         = "auto"
patches-source  = "anddea/revanced-patches"
uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
