# ======================================================================
# GLOBAL SETTINGS
# ======================================================================
patches-version = "latest"
dpi             = "nodpi anydpi 120-640dpi 240-480dpi 160-640dpi"
# parallel-jobs = 1

# ======================================================================
# VIDEO & STREAMING
# ======================================================================

# [YouTube]
# build-mode      = "apk"
# arch            = "arm64-v8a"
# uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# # archive-dlurl   = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [YouTube-Morphe]
# app-name        = "YouTube"
# patches-source  = "MorpheApp/morphe-patches"
# cli-source      = "MorpheApp/morphe-cli"
# rv-brand        = "Morphe"
# build-mode      = "apk"
# arch            = "arm64-v8a"
# uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# # archive-dlurl   = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [YouTube-anddea]
# enabled         = true
# app-name        = "YouTube-anddea"
# build-mode      = "apk"
# arch            = "all"
# version         = "auto"
# patches-source  = "anddea/revanced-patches"
# cli-source      = "j-hc/revanced-cli"
# uptodown-dlurl  = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

# ======================================================================
# MUSIC
# ======================================================================

# [Music]
# build-mode      = "apk"
# arch            = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# [Music-Morphe]
# app-name = "Music"
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "Morphe"
# build-mode      = "apk"
# arch            = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

# # [Music-anddea]
# # enabled         = true
# # app-name        = "Music-anddea"
# # build-mode      = "apk"
# # arch            = "arm64-v8a"
# # version         = "auto"
# # patches-source  = "anddea/revanced-patches"
# # cli-source      = "j-hc/revanced-cli"
# # uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
# # apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

# # ======================================================================
# # SOCIAL MEDIA & COMMUNICATION
# # ======================================================================

[Reddit]
enabled         = true
app-name        = "Reddit"
build-mode      = "apk"
version         = "auto"
uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"

# [Reddit-anddea]
# enabled         = true
# app-name        = "Reddit-anddea"
# build-mode      = "apk"
# version         = "auto"
# patches-source  = "anddea/revanced-patches"
# cli-source      = "j-hc/revanced-cli"
# uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"

[Reddit-Moprphe]
enabled         = true
app-name        = "Reddit-Moprphe"
build-mode      = "apk"
version         = "auto"
patches-source  = "MorpheApp/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"

[Twitter]
enabled         = true
app-name        = "Twitter"
build-mode      = "apk"
arch            = "arm64-v8a"
version         = "auto"
patches-source  = "crimera/piko"
# patches-version = "dev"
cli-source      = "revanced/revanced-cli"
uptodown-dlurl  = "https://twitter.en.uptodown.com/android"

[telegram]
enabled         = true
app-name        = "telegram"
build-mode      = "apk"
version         = "auto"
patches-source  = "Aunali321/ReVancedExperiments"
cli-source      = "revanced/revanced-cli"
uptodown-dlurl  = "https://telegram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram"


# ======================================================================
# SYSTEM & UTILITIES
# ======================================================================

[googlephotos]
enabled         = true
app-name        = "googlephotos"
build-mode      = "apk"
arch            = "arm64-v8a"
uptodown-dlurl  = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"

[irplus]
enabled         = true
app-name        = "irplus"
build-mode      = "apk"
version         = "auto"
patches-source  = "revanced/revanced-patches"
cli-source      = "revanced/revanced-cli"
uptodown-dlurl  = "https://irplus.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/binarymode/irplus-infrared-remote"

[Icon-Pack-Studio]
enabled         = true
app-name        = "Icon Pack Studio"
build-mode      = "apk"
version         = "auto"
patches-source  = "revanced/revanced-patches"
cli-source      = "revanced/revanced-cli"
uptodown-dlurl  = "https://icon-pack-studio.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio"

# ======================================================================
# DISABLED / ARCHIVED
# ======================================================================
# [YouTube-inotia00]
# [Music-inotia00]
# [Reddit-inotia00]
# [Spotify]
# [Google-News]
